services:
  - type: web
    name: devops-auto-healing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /